/* FIRST REPORT: Shows how often each type of room is rented with the most popular
room being noted first, sorted to the least popular */

SELECT STAY.ROOMID, ROOM.ROOMTYPE, COUNT(STAY.ROOMID)
FROM STAY, ROOM
WHERE STAY.ROOMID=ROOM.ROOMID 
GROUP BY STAY.ROOMID, ROOM.ROOMTYPE
ORDER BY COUNT DESC;

/* SECOND REPORT: Generates the occupants' end-of-month bills including the
occupant's name, address, date first rented, and total amount due */

/* February */
SELECT CUSTOMER.NAME, CUSTOMER.PERMANENTADDRESS, STAY.STARTDATE, STAY.AMOUNTDUE
FROM CUSTOMER, STAY
WHERE CUSTOMER.CUSTOMERID=STAY.CUSTOMERID AND
STAY.STARTDATE>='2/1/2021' AND STAY.STARTDATE<='2/28/2021'
ORDER BY STAY.STARTDATE;

/* March */
SELECT CUSTOMER.NAME, CUSTOMER.PERMANENTADDRESS, STAY.STARTDATE, STAY.AMOUNTDUE
FROM CUSTOMER, STAY
WHERE CUSTOMER.CUSTOMERID=STAY.CUSTOMERID AND
STAY.STARTDATE>='3/1/2021' AND STAY.STARTDATE<='3/31/2021'
ORDER BY STAY.STARTDATE;

/* April */
SELECT CUSTOMER.NAME, CUSTOMER.PERMANENTADDRESS, STAY.STARTDATE, STAY.AMOUNTDUE
FROM CUSTOMER, STAY
WHERE CUSTOMER.CUSTOMERID=STAY.CUSTOMERID AND
STAY.STARTDATE>='4/1/2021' AND STAY.STARTDATE<='4/30/2021'
ORDER BY STAY.STARTDATE;